### ISSUE TITLE
Not connecting to services in parallel?

### ISSUE THREAD

**Issue by hartwork** [clarketm/wait-for-it#6]
Hi!

The code at
https://github.com/clarketm/wait-for-it/blob/c742b6205c54620d2a4271c1606cb2ff5ea8cbb7/wait_for_it/wait_for_it.py#L49-L50 
connects to one service after another while it could connect to all of them in parallel and be done faster. Would you be interested in a pull request to make it run in parallel?

Best, Sebastian

**Comment by clarketm** [comment]
> Would you be interested in a pull request to make it run in parallel?

This sgtm, thanks for the suggestion and future contribution! I would prefer to put this feature behind a command-line flag (e.g. `--parallel`). This would maintain the current,  serial behavior unless the user sets the flag. This is mainly for backward compatibility. If down the road (during a major version bump) we want to make parallel execution the _default_ we can always invert this and add a `--serial` flag.

**Comment by hartwork** [comment]
If serial operation should remain supported, it would be nice to not need to duplicate too much (or any) code. The current way the alarm signalling is used would not work well as-is for a parallel approach. Let me demo an idea how to make it more friendly to adding parallelism later, as a dedicated initial pull request.

For parallelism, are you in favour or threads, processes or no preference? multiprocessing would allow us to get more of the CPU cake and open up new ways of enforcing timeouts.

**Comment by clarketm** [comment]
> If serial operation should remain supported, it would be nice to not need to duplicate too much (or any) code. 

I agree 💯 . If possible we should reduce code duplication, albeit IMO performance and portability are the most important factors, so if we need to duplicate some code that is 👌 . 

> The current way the alarm signalling is used would not work well as-is for a parallel approach. Let me demo an idea how to make it more friendly to adding parallelism later, as a dedicated initial pull request.
> 
> For parallelism, are you in favour or threads, processes or no preference? multiprocessing would allow us to get more of the CPU cake and open up new ways of enforcing timeouts.

My first thought is to take the _concurrency_ approach using something like `asyncio`. My justification for this is that I see this is more of a network-bound, rather than cpu-bound, task where most of the waiting is on connecting to the remote socket. TBH, I come from a JavaScript (i.e. single-threaded) background so I am a bit biased here and I do not have a strong opinion here either way. My main priority is **performance/speed** and **portability**. So, if we can get better performance from multithreading or multiprocessing I am all for it.

**Comment by hartwork** [comment]
Good idea on asyncio!

Let's see how you like the ground work at #9. Let's then go further towards parallelism step by step.
