### ISSUE TITLE
GitHub Actions CI and tests?

### ISSUE THREAD

**Issue by hartwork** [clarketm/wait-for-it#7]
Hi!

Are there plans to add smoke tests and integration with GitHub Action to make sure that future pull request cannot break this tool? Would you be interested in a pull request to do that?

Best, Sebastian

**Comment by clarketm** [comment]
> Are there plans to add smoke tests and integration with GitHub Action to make sure that future pull request cannot break this tool? Would you be interested in a pull request to do that?

The goal early on was definitely to write tests (at least unit tests) but because the program was so small (and changed infrequently) I never got around to it. WTBS, will PRs coming in and active users of this script, I think now is a great time to add tests. If you already have a test(s) written, or want to contribute some that would be amazing! I will create an issue for getting the CI setup.

**Comment by clarketm** [comment]
Added a simple set of actions to run format, lint, and unit tests in https://github.com/clarketm/wait-for-it/pull/14.
